name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Checkout gradual-sdk-spec
        uses: actions/checkout@v4
        with:
          repository: elijahnikov/gradual-sdk-spec
          path: ../gradual-sdk-spec

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Build
        run: cargo build

      - name: Test
        run: cargo test

      - name: Clippy
        run: cargo clippy -- -D warnings
